version: "3.9"
services:
  back-office:
    image: back-office-image
    build:
      context: .
      dockerfile: ./build/docker/back-office/Dockerfile
    ports:
      - 3002:3000
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/MusicShop
    depends_on:
      - db
  rental:
    image: rental-image
    build:
      context: .
      dockerfile: ./build/docker/rental/Dockerfile
    ports:
      - 3001:3000
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/MusicShop
    depends_on:
      - db
      - back-office
  rental-frontend:
    image: rental-app
    build:
      context: .
      dockerfile: ./build/docker/rental-app/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - rental
      - back-office
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: MusicShop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
